version: "3.9"
services:
  postgres:
    image: postgres:14
    container_name: snoop-postgres
    ports:
      - "6543:5432"  # host:container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - snoop_etl_project_pgdata:/var/lib/postgresql/data
      - ./ddl/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  etl:
    build: .
    depends_on:
      - postgres
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/app

volumes:
  snoop_etl_project_pgdata:
